apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-operator-metrics
  namespace: crypto-infra
  labels:
    app: spark-operator
    app.kubernetes.io/name: spark-kubernetes-operator
    release: crypto-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: spark-kubernetes-operator
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - crypto-infra

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-driver-metrics
  namespace: crypto-infra
  labels:
    app: spark-applications
    release: crypto-monitoring
spec:
  selector:
    matchLabels:
      spark-role: driver
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - crypto-infra

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-executor-metrics
  namespace: crypto-infra
  labels:
    app: spark-applications
    release: crypto-monitoring
spec:
  selector:
    matchLabels:
      spark-role: executor
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - crypto-infra

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: spark-pods-metrics
  namespace: crypto-infra
  labels:
    app: spark-applications
    release: crypto-monitoring
spec:
  selector:
    matchExpressions:
    - key: spark-role
      operator: In
      values:
      - driver
      - executor
  podMetricsEndpoints:
  - port: metrics
    interval: 30s
    path: /metrics
  namespaceSelector:
    matchNames:
    - crypto-infra

