apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-spark-application-role
  namespace: crypto-infra
rules:
  - apiGroups:
      - "sparkoperator.k8s.io"
    resources:
      - "sparkapplications"
    verbs:
      - "create"
      - "get"
      - "list"
      - "watch"
      - "update"
      - "patch"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-spark-application-rolebinding
  namespace: crypto-infra
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: airflow-spark-application-role
subjects:
  - kind: ServiceAccount
    name: airflow-worker 
    namespace: crypto-infra