apiVersion: v1
kind: Service
metadata:
  name: backend-fastapi-service
  namespace: crypto-app
spec:
  type: ClusterIP
  selector:
    app: backend-fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000


