apiVersion: v1
kind: Service
metadata:
  name: frontend-next-service
  namespace: crypto-app
spec:
  type: ClusterIP
  selector:
    app: frontend-next
  ports:
    - name: http
      port: 3000
      targetPort: 3000


