apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crypto-frontend-ingress
  namespace: crypto-app
spec:
  ingressClassName: nginx
  rules:
    - host: crypto.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-next-service
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crypto-backend-ingress
  namespace: crypto-app
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: crypto.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: backend-fastapi-service
                port:
                  number: 8000