apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-model-storage
  namespace: crypto-infra
spec:
  accessModes:
    - ReadWriteOnce  # Minikube standard storage class supports RWO
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard

