apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow-statsd
  namespace: crypto-infra
  labels:
    app: airflow
    component: statsd
    release: crypto-monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: airflow
      app.kubernetes.io/component: statsd
  endpoints:
    - port: statsd-scrape
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
  namespaceSelector:
    matchNames:
      - crypto-infra

