apiVersion: v1
kind: Service
metadata:
  name: spark-operator-metrics
  namespace: crypto-infra
  labels:
    app.kubernetes.io/name: spark-operator
    app: spark-operator
    release: crypto-monitoring
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 19090
      targetPort: 19090
      protocol: TCP
  selector:
    app.kubernetes.io/name: spark-kubernetes-operator
    app.kubernetes.io/component: operator-deployment

