apiVersion: v1
kind: ConfigMap
metadata:
  name: crypto-kafka-config
  namespace: kafka
data:
  KAFKA_BROKER: "my-cluster-kafka-bootstrap:9092"  # Internal service name cá»§a Kafka
  KAFKA_TOPIC: "crypto_kline_1m"
  CONSUMER_GROUP: "crypto_group"


